Регистрация
htmlacademy-yii/360863-task-force-2 pull request #13
Opened 2022-06-02 22:48 UTC by Leonid-Grishin

---
:mortar_board: [Регистрация](https://up.htmlacademy.ru/yii/2/user/360863/tasks/15)

2022-06-02 22:49 UTC, Leonid-Grishin commented on controllers/RegistrationController.php
> +            $user->name = $registration->name; /*а нужно тут делать что то с безопасностью?*/
нужно ли тут делать что то с безопасностью?

2022-06-02 22:49 UTC, Leonid-Grishin commented on controllers/LandingController.php
> +        $this->view->title = 'Главная страница'; /*и так тоже не передается Tilte*/
почему-то не могу заполнить title, вроде тоже самое как и на других страница, но не выходит

2022-06-02 22:51 UTC, Leonid-Grishin commented on views/landing/index.php
> +$this->title = 'Главная страница'; /*а почему не передается title?*/
попробовал прямо вью тоже не передается title

2022-06-02 22:53 UTC, Leonid-Grishin commented on views/registration/index.php
> +            <?= $form->field($registration, 'isWorker')->checkbox(['uncheck' => 0, 'value' => 1, 'checked' => true]); ?> <!--почему-то не добавляется class 'control-label' к label-->
не получилось добавить стиль к лейблу чекбоксу. всем полям добавился класс через fieldConfig а тут нет

2022-06-02 22:55 UTC, Leonid-Grishin commented on views/registration/index.php
> +            <?= Html::submitInput('Создать аккаунт', ['class' => 'button button--blue']) ;?><!-- тут чтоже со стилем не выходит-->
и тут со стилями не получилось. если я правильно понял стили применяются к полю с типом type='buttton', а нам же нужен type = 'submit', правильно? а как тогда стили переключить?

2022-06-06 09:03 UTC, webmayak requested changes

2022-06-06 09:03 UTC, webmayak commented on config/web.php
> +                '' => 'landing/index',
такое правильнее сделать через параметр `defaultRoute`, см. [тут](https://www.yiiframework.com/doc/api/2.0/yii-base-module#$defaultRoute-detail) и [тут](https://www.yiiframework.com/doc/guide/2.0/en/runtime-routing)

2022-06-06 09:03 UTC, webmayak commented on controllers/LandingController.php
> +        $this->view->title = 'Главная страница'; /*и так тоже не передается Tilte*/
у тебя же он ещё и задаётся [во вью](https://github.com/htmlacademy-yii/360863-task-force-2/blob/c0ebd2434b9539bc62e7313311c091f8a6b3e1e0/views/site/index.php)? возможно, в этом причина как раз

2022-06-06 09:03 UTC, webmayak commented on controllers/RegistrationController.php
> +            $user->name = $registration->name; /*а нужно тут делать что то с безопасностью?*/
за безопасность тут должна отвечать валидация внутри `$registration` и `$user`, пока вроде бы всё с этим нормально

2022-06-06 09:03 UTC, webmayak commented on migrations/m220602_200809_add_is_worker_column_to_user_table.php
> +        $this->addColumn('user', 'is_worker', $this->integer(1));
для такого типа полей есть метод `boolean()`, см. [в доке](https://www.yiiframework.com/doc/api/2.0/yii-db-migration#boolean()-detail)

2022-06-06 09:03 UTC, webmayak commented on views/layouts/main.php
> +        <a href='<?= Url::to(['/']); ?>' class="header-logo">
есть метод `Url::home()`, см. [в доке](https://www.yiiframework.com/doc/api/2.0/yii-helpers-url#home()-detail)

2022-06-06 09:03 UTC, webmayak commented on views/layouts/main.php
> +    <?php if(Yii::$app->controller->id !== 'registration'): ?>
тут проверка на котроллер не есть хорошо, надо использовать `Yii::$app->user->isGuest`

2022-06-06 09:03 UTC, webmayak commented on views/registration/index.php
> +            <?= Html::submitInput('Создать аккаунт', ['class' => 'button button--blue']) ;?><!-- тут чтоже со стилем не выходит-->
да, похоже на правду =) попробуй `Html::submitButton()`

2022-06-06 09:03 UTC, webmayak commented on views/tasks/view.php
> +            <img class="map" src="<?= Url::to(['@web/img/map.png']); ?>"  width="725" height="346" alt="Новый арбат, 23, к. 1">
можно без алиаса `@web`:

```suggestion
            <img class="map" src="<?= Url::to(['/img/map.png']); ?>"  width="725" height="346" alt="Новый арбат, 23, к. 1">
```

2022-06-06 15:40 UTC, merged